# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_data_mongodb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_data_mongodb.proto',
  package='com.richisland.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x15pb_data_mongodb.proto\x12\x14\x63om.richisland.proto\"4\n\x08m_config\x12\x12\n\nconfig_key\x18\x01 \x01(\t\x12\x14\n\x0c\x63onfig_value\x18\x02 \x01(\x0c\x62\x06proto3')
)




_M_CONFIG = _descriptor.Descriptor(
  name='m_config',
  full_name='com.richisland.proto.m_config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_key', full_name='com.richisland.proto.m_config.config_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config_value', full_name='com.richisland.proto.m_config.config_value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['m_config'] = _M_CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

m_config = _reflection.GeneratedProtocolMessageType('m_config', (_message.Message,), dict(
  DESCRIPTOR = _M_CONFIG,
  __module__ = 'pb_data_mongodb_pb2'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.m_config)
  ))

_sym_db.RegisterMessage(m_config)


# @@protoc_insertion_point(module_scope)
