# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_config_modbus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_config_tag as pb__config__tag__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_config_modbus.proto',
  package='com.richisland.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x16pb_config_modbus.proto\x12\x14\x63om.richisland.proto\x1a\x13pb_config_tag.proto\"\xfb\x02\n\x10pb_config_modbus\x12\x11\n\tmodbus_id\x18\x01 \x01(\x05\x12:\n\x0c\x63ollect_type\x18\x02 \x01(\x0e\x32$.com.richisland.proto.pb_modbus_type\x12\x15\n\rcomm_overtime\x18\x03 \x01(\x05\x12\x15\n\rmodbus_tcp_ip\x18\x04 \x01(\t\x12\x17\n\x0fmodbus_tcp_port\x18\x05 \x01(\x05\x12\x1b\n\x13max_registor_number\x18\x06 \x01(\x05\x12<\n\rmodbus_groups\x18\x07 \x03(\x0b\x32%.com.richisland.proto.pb_modbus_group\x12\x38\n\x0bmodbus_tags\x18\x08 \x03(\x0b\x32#.com.richisland.proto.pb_config_tag\x12<\n\rmodbus_meters\x18\t \x03(\x0b\x32%.com.richisland.proto.pb_modbus_meter\"\x85\x01\n\x0fpb_modbus_group\x12\x10\n\x08group_id\x18\x01 \x01(\x05\x12\x12\n\ngroup_name\x18\x02 \x01(\t\x12\x15\n\rcollect_cycle\x18\x03 \x01(\x05\x12\x35\n\x08opc_tags\x18\x04 \x03(\x0b\x32#.com.richisland.proto.pb_config_tag\"~\n\x0fpb_modbus_meter\x12\x0e\n\x06tag_id\x18\x01 \x01(\x05\x12\x15\n\rfunction_code\x18\x02 \x01(\x05\x12\x13\n\x0bmodbus_addr\x18\x03 \x01(\x05\x12\x16\n\x0estart_register\x18\x04 \x01(\x05\x12\x17\n\x0fregister_number\x18\x05 \x01(\x05*N\n\x0epb_modbus_type\x12\x0e\n\nMODBUS_RTU\x10\x00\x12\x10\n\x0cMODBUS_ASCII\x10\x01\x12\x0b\n\x07TCP_RTU\x10\x02\x12\r\n\tTCP_ASCII\x10\x03\x62\x06proto3')
  ,
  dependencies=[pb__config__tag__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PB_MODBUS_TYPE = _descriptor.EnumDescriptor(
  name='pb_modbus_type',
  full_name='com.richisland.proto.pb_modbus_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODBUS_RTU', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODBUS_ASCII', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TCP_RTU', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TCP_ASCII', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=715,
  serialized_end=793,
)
_sym_db.RegisterEnumDescriptor(_PB_MODBUS_TYPE)

pb_modbus_type = enum_type_wrapper.EnumTypeWrapper(_PB_MODBUS_TYPE)
MODBUS_RTU = 0
MODBUS_ASCII = 1
TCP_RTU = 2
TCP_ASCII = 3



_PB_CONFIG_MODBUS = _descriptor.Descriptor(
  name='pb_config_modbus',
  full_name='com.richisland.proto.pb_config_modbus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modbus_id', full_name='com.richisland.proto.pb_config_modbus.modbus_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collect_type', full_name='com.richisland.proto.pb_config_modbus.collect_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comm_overtime', full_name='com.richisland.proto.pb_config_modbus.comm_overtime', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modbus_tcp_ip', full_name='com.richisland.proto.pb_config_modbus.modbus_tcp_ip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modbus_tcp_port', full_name='com.richisland.proto.pb_config_modbus.modbus_tcp_port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_registor_number', full_name='com.richisland.proto.pb_config_modbus.max_registor_number', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modbus_groups', full_name='com.richisland.proto.pb_config_modbus.modbus_groups', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modbus_tags', full_name='com.richisland.proto.pb_config_modbus.modbus_tags', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modbus_meters', full_name='com.richisland.proto.pb_config_modbus.modbus_meters', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=449,
)


_PB_MODBUS_GROUP = _descriptor.Descriptor(
  name='pb_modbus_group',
  full_name='com.richisland.proto.pb_modbus_group',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_id', full_name='com.richisland.proto.pb_modbus_group.group_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group_name', full_name='com.richisland.proto.pb_modbus_group.group_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collect_cycle', full_name='com.richisland.proto.pb_modbus_group.collect_cycle', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opc_tags', full_name='com.richisland.proto.pb_modbus_group.opc_tags', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=585,
)


_PB_MODBUS_METER = _descriptor.Descriptor(
  name='pb_modbus_meter',
  full_name='com.richisland.proto.pb_modbus_meter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_id', full_name='com.richisland.proto.pb_modbus_meter.tag_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='function_code', full_name='com.richisland.proto.pb_modbus_meter.function_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modbus_addr', full_name='com.richisland.proto.pb_modbus_meter.modbus_addr', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_register', full_name='com.richisland.proto.pb_modbus_meter.start_register', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='register_number', full_name='com.richisland.proto.pb_modbus_meter.register_number', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=587,
  serialized_end=713,
)

_PB_CONFIG_MODBUS.fields_by_name['collect_type'].enum_type = _PB_MODBUS_TYPE
_PB_CONFIG_MODBUS.fields_by_name['modbus_groups'].message_type = _PB_MODBUS_GROUP
_PB_CONFIG_MODBUS.fields_by_name['modbus_tags'].message_type = pb__config__tag__pb2._PB_CONFIG_TAG
_PB_CONFIG_MODBUS.fields_by_name['modbus_meters'].message_type = _PB_MODBUS_METER
_PB_MODBUS_GROUP.fields_by_name['opc_tags'].message_type = pb__config__tag__pb2._PB_CONFIG_TAG
DESCRIPTOR.message_types_by_name['pb_config_modbus'] = _PB_CONFIG_MODBUS
DESCRIPTOR.message_types_by_name['pb_modbus_group'] = _PB_MODBUS_GROUP
DESCRIPTOR.message_types_by_name['pb_modbus_meter'] = _PB_MODBUS_METER
DESCRIPTOR.enum_types_by_name['pb_modbus_type'] = _PB_MODBUS_TYPE

pb_config_modbus = _reflection.GeneratedProtocolMessageType('pb_config_modbus', (_message.Message,), dict(
  DESCRIPTOR = _PB_CONFIG_MODBUS,
  __module__ = 'pb_config_modbus'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_config_modbus)
  ))
_sym_db.RegisterMessage(pb_config_modbus)

pb_modbus_group = _reflection.GeneratedProtocolMessageType('pb_modbus_group', (_message.Message,), dict(
  DESCRIPTOR = _PB_MODBUS_GROUP,
  __module__ = 'pb_config_modbus'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_modbus_group)
  ))
_sym_db.RegisterMessage(pb_modbus_group)

pb_modbus_meter = _reflection.GeneratedProtocolMessageType('pb_modbus_meter', (_message.Message,), dict(
  DESCRIPTOR = _PB_MODBUS_METER,
  __module__ = 'pb_config_modbus'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_modbus_meter)
  ))
_sym_db.RegisterMessage(pb_modbus_meter)


# @@protoc_insertion_point(module_scope)
