# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_config_opcalarm_client.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_config_opcalarm_client.proto',
  package='com.richisland.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x1fpb_config_opcalarm_client.proto\x12\x14\x63om.richisland.proto\"\xff\x01\n\x19pb_config_opcalarm_client\x12\x1a\n\x12opcalarm_client_id\x18\x01 \x01(\x05\x12\x16\n\x0eserver_address\x18\x02 \x01(\t\x12\x16\n\x0eserver_prog_id\x18\x03 \x01(\t\x12\x14\n\x0cserver_clsid\x18\x04 \x01(\t\x12\x15\n\rserver_domain\x18\x05 \x01(\t\x12\x13\n\x0bserver_user\x18\x06 \x01(\t\x12\x17\n\x0fserver_password\x18\x07 \x01(\t\x12;\n\x0csubscription\x18\x08 \x03(\x0b\x32%.com.richisland.proto.pb_subscription\"\xc1\x01\n\x0fpb_subscription\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\x05\x12\x19\n\x11subscription_name\x18\x02 \x01(\t\x12\x0e\n\x06\x65nable\x18\x03 \x01(\x08\x12\x13\n\x0bupdate_rate\x18\x04 \x01(\x05\x12\x10\n\x08max_size\x18\x05 \x01(\x05\x12\x12\n\nevent_type\x18\x06 \x01(\t\x12\x17\n\x0fhigh_serverrity\x18\x07 \x01(\x05\x12\x16\n\x0elow_serverrity\x18\x08 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PB_CONFIG_OPCALARM_CLIENT = _descriptor.Descriptor(
  name='pb_config_opcalarm_client',
  full_name='com.richisland.proto.pb_config_opcalarm_client',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opcalarm_client_id', full_name='com.richisland.proto.pb_config_opcalarm_client.opcalarm_client_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_address', full_name='com.richisland.proto.pb_config_opcalarm_client.server_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_prog_id', full_name='com.richisland.proto.pb_config_opcalarm_client.server_prog_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_clsid', full_name='com.richisland.proto.pb_config_opcalarm_client.server_clsid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_domain', full_name='com.richisland.proto.pb_config_opcalarm_client.server_domain', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_user', full_name='com.richisland.proto.pb_config_opcalarm_client.server_user', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_password', full_name='com.richisland.proto.pb_config_opcalarm_client.server_password', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subscription', full_name='com.richisland.proto.pb_config_opcalarm_client.subscription', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=313,
)


_PB_SUBSCRIPTION = _descriptor.Descriptor(
  name='pb_subscription',
  full_name='com.richisland.proto.pb_subscription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscription_id', full_name='com.richisland.proto.pb_subscription.subscription_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subscription_name', full_name='com.richisland.proto.pb_subscription.subscription_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable', full_name='com.richisland.proto.pb_subscription.enable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='update_rate', full_name='com.richisland.proto.pb_subscription.update_rate', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_size', full_name='com.richisland.proto.pb_subscription.max_size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='com.richisland.proto.pb_subscription.event_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='high_serverrity', full_name='com.richisland.proto.pb_subscription.high_serverrity', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low_serverrity', full_name='com.richisland.proto.pb_subscription.low_serverrity', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=509,
)

_PB_CONFIG_OPCALARM_CLIENT.fields_by_name['subscription'].message_type = _PB_SUBSCRIPTION
DESCRIPTOR.message_types_by_name['pb_config_opcalarm_client'] = _PB_CONFIG_OPCALARM_CLIENT
DESCRIPTOR.message_types_by_name['pb_subscription'] = _PB_SUBSCRIPTION

pb_config_opcalarm_client = _reflection.GeneratedProtocolMessageType('pb_config_opcalarm_client', (_message.Message,), dict(
  DESCRIPTOR = _PB_CONFIG_OPCALARM_CLIENT,
  __module__ = 'pb_config_opcalarm_client'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_config_opcalarm_client)
  ))
_sym_db.RegisterMessage(pb_config_opcalarm_client)

pb_subscription = _reflection.GeneratedProtocolMessageType('pb_subscription', (_message.Message,), dict(
  DESCRIPTOR = _PB_SUBSCRIPTION,
  __module__ = 'pb_config_opcalarm_client'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_subscription)
  ))
_sym_db.RegisterMessage(pb_subscription)


# @@protoc_insertion_point(module_scope)
