# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_config_mongodb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_config_mongodb.proto',
  package='com.richisland.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x17pb_config_mongodb.proto\x12\x14\x63om.richisland.proto\"\xd7\x01\n\x11pb_config_mongodb\x12\x12\n\nmongodb_id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x11\n\tuser_name\x18\x04 \x01(\t\x12\x15\n\ruser_password\x18\x05 \x01(\t\x12\r\n\x05\x63ycle\x18\x06 \x01(\x05\x12\x15\n\rdatabase_name\x18\x07 \x01(\t\x12\x17\n\x0f\x63ollection_name\x18\x08 \x01(\t\x12\x12\n\nfield_name\x18\t \x01(\t\x12\x17\n\x0fsearch_key_list\x18\n \x03(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PB_CONFIG_MONGODB = _descriptor.Descriptor(
  name='pb_config_mongodb',
  full_name='com.richisland.proto.pb_config_mongodb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mongodb_id', full_name='com.richisland.proto.pb_config_mongodb.mongodb_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='com.richisland.proto.pb_config_mongodb.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='com.richisland.proto.pb_config_mongodb.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='com.richisland.proto.pb_config_mongodb.user_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_password', full_name='com.richisland.proto.pb_config_mongodb.user_password', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cycle', full_name='com.richisland.proto.pb_config_mongodb.cycle', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='database_name', full_name='com.richisland.proto.pb_config_mongodb.database_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collection_name', full_name='com.richisland.proto.pb_config_mongodb.collection_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field_name', full_name='com.richisland.proto.pb_config_mongodb.field_name', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='search_key_list', full_name='com.richisland.proto.pb_config_mongodb.search_key_list', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=265,
)

DESCRIPTOR.message_types_by_name['pb_config_mongodb'] = _PB_CONFIG_MONGODB

pb_config_mongodb = _reflection.GeneratedProtocolMessageType('pb_config_mongodb', (_message.Message,), dict(
  DESCRIPTOR = _PB_CONFIG_MONGODB,
  __module__ = 'pb_config_mongodb'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_config_mongodb)
  ))
_sym_db.RegisterMessage(pb_config_mongodb)


# @@protoc_insertion_point(module_scope)
