# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_config_database.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_config_database.proto',
  package='com.richisland.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x18pb_config_database.proto\x12\x14\x63om.richisland.proto\"\x8a\x01\n\x12pb_config_database\x12\x1a\n\x12\x64\x61tabase_config_id\x18\x01 \x01(\x05\x12\x1c\n\x14\x64\x61tabase_config_name\x18\x02 \x01(\t\x12:\n\x0f\x64\x61tabase_config\x18\x03 \x03(\x0b\x32!.com.richisland.proto.pb_database\"c\n\x0bpb_database\x12\x13\n\x0bserver_name\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x15\n\ruser_password\x18\x03 \x01(\t\x12\x15\n\rdatabase_name\x18\x04 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PB_CONFIG_DATABASE = _descriptor.Descriptor(
  name='pb_config_database',
  full_name='com.richisland.proto.pb_config_database',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database_config_id', full_name='com.richisland.proto.pb_config_database.database_config_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='database_config_name', full_name='com.richisland.proto.pb_config_database.database_config_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='database_config', full_name='com.richisland.proto.pb_config_database.database_config', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=189,
)


_PB_DATABASE = _descriptor.Descriptor(
  name='pb_database',
  full_name='com.richisland.proto.pb_database',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_name', full_name='com.richisland.proto.pb_database.server_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='com.richisland.proto.pb_database.user_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_password', full_name='com.richisland.proto.pb_database.user_password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='database_name', full_name='com.richisland.proto.pb_database.database_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=290,
)

_PB_CONFIG_DATABASE.fields_by_name['database_config'].message_type = _PB_DATABASE
DESCRIPTOR.message_types_by_name['pb_config_database'] = _PB_CONFIG_DATABASE
DESCRIPTOR.message_types_by_name['pb_database'] = _PB_DATABASE

pb_config_database = _reflection.GeneratedProtocolMessageType('pb_config_database', (_message.Message,), dict(
  DESCRIPTOR = _PB_CONFIG_DATABASE,
  __module__ = 'pb_config_database'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_config_database)
  ))
_sym_db.RegisterMessage(pb_config_database)

pb_database = _reflection.GeneratedProtocolMessageType('pb_database', (_message.Message,), dict(
  DESCRIPTOR = _PB_DATABASE,
  __module__ = 'pb_config_database'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_database)
  ))
_sym_db.RegisterMessage(pb_database)


# @@protoc_insertion_point(module_scope)
