# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_config_device.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_config_device.proto',
  package='com.richisland.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x16pb_config_device.proto\x12\x14\x63om.richisland.proto\"\xfb\x02\n\x10pb_config_device\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x03 \x01(\t\x12\x38\n\x0bsend_config\x18\x04 \x01(\x0b\x32#.com.richisland.proto.pb_net_config\x12\x38\n\x0b\x63oll_config\x18\x05 \x01(\x0b\x32#.com.richisland.proto.pb_net_config\x12\x37\n\ncom_config\x18\x06 \x01(\x0b\x32#.com.richisland.proto.pb_com_config\x12<\n\x0fmain_ntp_config\x18\x07 \x01(\x0b\x32#.com.richisland.proto.pb_ntp_config\x12?\n\x12reserve_ntp_config\x18\x08 \x01(\x0b\x32#.com.richisland.proto.pb_ntp_config\"_\n\rpb_net_config\x12\x10\n\x08net_name\x18\x01 \x01(\t\x12\x0c\n\x04ipv4\x18\x02 \x01(\t\x12\x0c\n\x04ipv6\x18\x03 \x01(\t\x12\x0f\n\x07netmask\x18\x04 \x01(\t\x12\x0f\n\x07gateway\x18\x05 \x01(\t\"\x9b\x01\n\rpb_com_config\x12\x0f\n\x07portnum\x18\x01 \x01(\t\x12\x0c\n\x04\x62\x61ud\x18\x02 \x01(\x05\x12\x34\n\x06parity\x18\x03 \x01(\x0e\x32$.com.richisland.proto.pb_parity_mode\x12\x0f\n\x07\x64\x61tabit\x18\x04 \x01(\x05\x12\x0f\n\x07stopbit\x18\x05 \x01(\x02\x12\x13\n\x0bhard_stream\x18\x06 \x01(\x05\"5\n\rpb_ntp_config\x12\x10\n\x08serverip\x18\x01 \x01(\t\x12\x12\n\nserverport\x18\x02 \x01(\x05*B\n\x0epb_parity_mode\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03ODD\x10\x01\x12\x08\n\x04\x45VEN\x10\x02\x12\x08\n\x04MARK\x10\x03\x12\t\n\x05SPACE\x10\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PB_PARITY_MODE = _descriptor.EnumDescriptor(
  name='pb_parity_mode',
  full_name='com.richisland.proto.pb_parity_mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ODD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVEN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MARK', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPACE', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=740,
  serialized_end=806,
)
_sym_db.RegisterEnumDescriptor(_PB_PARITY_MODE)

pb_parity_mode = enum_type_wrapper.EnumTypeWrapper(_PB_PARITY_MODE)
NONE = 0
ODD = 1
EVEN = 2
MARK = 3
SPACE = 4



_PB_CONFIG_DEVICE = _descriptor.Descriptor(
  name='pb_config_device',
  full_name='com.richisland.proto.pb_config_device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='com.richisland.proto.pb_config_device.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_name', full_name='com.richisland.proto.pb_config_device.device_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='com.richisland.proto.pb_config_device.device_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='send_config', full_name='com.richisland.proto.pb_config_device.send_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coll_config', full_name='com.richisland.proto.pb_config_device.coll_config', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='com_config', full_name='com.richisland.proto.pb_config_device.com_config', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='main_ntp_config', full_name='com.richisland.proto.pb_config_device.main_ntp_config', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reserve_ntp_config', full_name='com.richisland.proto.pb_config_device.reserve_ntp_config', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=428,
)


_PB_NET_CONFIG = _descriptor.Descriptor(
  name='pb_net_config',
  full_name='com.richisland.proto.pb_net_config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='net_name', full_name='com.richisland.proto.pb_net_config.net_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ipv4', full_name='com.richisland.proto.pb_net_config.ipv4', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ipv6', full_name='com.richisland.proto.pb_net_config.ipv6', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='netmask', full_name='com.richisland.proto.pb_net_config.netmask', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gateway', full_name='com.richisland.proto.pb_net_config.gateway', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=525,
)


_PB_COM_CONFIG = _descriptor.Descriptor(
  name='pb_com_config',
  full_name='com.richisland.proto.pb_com_config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='portnum', full_name='com.richisland.proto.pb_com_config.portnum', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baud', full_name='com.richisland.proto.pb_com_config.baud', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parity', full_name='com.richisland.proto.pb_com_config.parity', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='databit', full_name='com.richisland.proto.pb_com_config.databit', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stopbit', full_name='com.richisland.proto.pb_com_config.stopbit', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hard_stream', full_name='com.richisland.proto.pb_com_config.hard_stream', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=683,
)


_PB_NTP_CONFIG = _descriptor.Descriptor(
  name='pb_ntp_config',
  full_name='com.richisland.proto.pb_ntp_config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverip', full_name='com.richisland.proto.pb_ntp_config.serverip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverport', full_name='com.richisland.proto.pb_ntp_config.serverport', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=738,
)

_PB_CONFIG_DEVICE.fields_by_name['send_config'].message_type = _PB_NET_CONFIG
_PB_CONFIG_DEVICE.fields_by_name['coll_config'].message_type = _PB_NET_CONFIG
_PB_CONFIG_DEVICE.fields_by_name['com_config'].message_type = _PB_COM_CONFIG
_PB_CONFIG_DEVICE.fields_by_name['main_ntp_config'].message_type = _PB_NTP_CONFIG
_PB_CONFIG_DEVICE.fields_by_name['reserve_ntp_config'].message_type = _PB_NTP_CONFIG
_PB_COM_CONFIG.fields_by_name['parity'].enum_type = _PB_PARITY_MODE
DESCRIPTOR.message_types_by_name['pb_config_device'] = _PB_CONFIG_DEVICE
DESCRIPTOR.message_types_by_name['pb_net_config'] = _PB_NET_CONFIG
DESCRIPTOR.message_types_by_name['pb_com_config'] = _PB_COM_CONFIG
DESCRIPTOR.message_types_by_name['pb_ntp_config'] = _PB_NTP_CONFIG
DESCRIPTOR.enum_types_by_name['pb_parity_mode'] = _PB_PARITY_MODE

pb_config_device = _reflection.GeneratedProtocolMessageType('pb_config_device', (_message.Message,), dict(
  DESCRIPTOR = _PB_CONFIG_DEVICE,
  __module__ = 'pb_config_device'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_config_device)
  ))
_sym_db.RegisterMessage(pb_config_device)

pb_net_config = _reflection.GeneratedProtocolMessageType('pb_net_config', (_message.Message,), dict(
  DESCRIPTOR = _PB_NET_CONFIG,
  __module__ = 'pb_config_device'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_net_config)
  ))
_sym_db.RegisterMessage(pb_net_config)

pb_com_config = _reflection.GeneratedProtocolMessageType('pb_com_config', (_message.Message,), dict(
  DESCRIPTOR = _PB_COM_CONFIG,
  __module__ = 'pb_config_device'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_com_config)
  ))
_sym_db.RegisterMessage(pb_com_config)

pb_ntp_config = _reflection.GeneratedProtocolMessageType('pb_ntp_config', (_message.Message,), dict(
  DESCRIPTOR = _PB_NTP_CONFIG,
  __module__ = 'pb_config_device'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_ntp_config)
  ))
_sym_db.RegisterMessage(pb_ntp_config)


# @@protoc_insertion_point(module_scope)
