# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_data_sensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb_config_tag as pb__config__tag__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_data_sensor.proto',
  package='com.richisland.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x14pb_data_sensor.proto\x12\x14\x63om.richisland.proto\x1a\x13pb_config_tag.proto\"\xf4\x01\n\x0epb_data_sensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x30\n\x04type\x18\x02 \x01(\x0e\x32\".com.richisland.proto.pb_data_type\x12\x0c\n\x04size\x18\x03 \x01(\x05\x12\r\n\x05value\x18\x04 \x01(\x0c\x12\x0c\n\x04time\x18\x05 \x01(\x03\x12\x0f\n\x07quality\x18\x06 \x01(\x05\x12\x34\n\x06status\x18\x07 \x01(\x0e\x32$.com.richisland.proto.pb_data_status\x12\x30\n\x04unit\x18\x08 \x01(\x0e\x32\".com.richisland.proto.pb_data_unit*>\n\x0epb_data_status\x12\x08\n\x04GOOD\x10\x00\x12\x07\n\x03\x42\x41\x44\x10\x01\x12\x0b\n\x07INVALID\x10\x02\x12\x0c\n\x08NONEXIST\x10\x03\x62\x06proto3')
  ,
  dependencies=[pb__config__tag__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PB_DATA_STATUS = _descriptor.EnumDescriptor(
  name='pb_data_status',
  full_name='com.richisland.proto.pb_data_status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GOOD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NONEXIST', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=314,
  serialized_end=376,
)
_sym_db.RegisterEnumDescriptor(_PB_DATA_STATUS)

pb_data_status = enum_type_wrapper.EnumTypeWrapper(_PB_DATA_STATUS)
GOOD = 0
BAD = 1
INVALID = 2
NONEXIST = 3



_PB_DATA_SENSOR = _descriptor.Descriptor(
  name='pb_data_sensor',
  full_name='com.richisland.proto.pb_data_sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.richisland.proto.pb_data_sensor.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.richisland.proto.pb_data_sensor.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='com.richisland.proto.pb_data_sensor.size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.richisland.proto.pb_data_sensor.value', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='com.richisland.proto.pb_data_sensor.time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quality', full_name='com.richisland.proto.pb_data_sensor.quality', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='com.richisland.proto.pb_data_sensor.status', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit', full_name='com.richisland.proto.pb_data_sensor.unit', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=312,
)

_PB_DATA_SENSOR.fields_by_name['type'].enum_type = pb__config__tag__pb2._PB_DATA_TYPE
_PB_DATA_SENSOR.fields_by_name['status'].enum_type = _PB_DATA_STATUS
_PB_DATA_SENSOR.fields_by_name['unit'].enum_type = pb__config__tag__pb2._PB_DATA_UNIT
DESCRIPTOR.message_types_by_name['pb_data_sensor'] = _PB_DATA_SENSOR
DESCRIPTOR.enum_types_by_name['pb_data_status'] = _PB_DATA_STATUS

pb_data_sensor = _reflection.GeneratedProtocolMessageType('pb_data_sensor', (_message.Message,), dict(
  DESCRIPTOR = _PB_DATA_SENSOR,
  __module__ = 'pb_data_sensor'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_data_sensor)
  ))
_sym_db.RegisterMessage(pb_data_sensor)


# @@protoc_insertion_point(module_scope)
