# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_data_opcalarm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb_data_opcalarm.proto',
  package='com.richisland.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x16pb_data_opcalarm.proto\x12\x14\x63om.richisland.proto\"\x83\x04\n\x10pb_data_opcalarm\x12\x18\n\x10opcalarm_data_id\x18\x01 \x01(\x05\x12\x12\n\nis_publish\x18\x02 \x01(\x08\x12\x34\n\nevent_type\x18\x03 \x01(\x0e\x32 .com.richisland.proto.event_type\x12\x10\n\x08severity\x18\x04 \x01(\x05\x12\x16\n\x0eserver_address\x18\x05 \x01(\t\x12\x16\n\x0eserver_prog_id\x18\x06 \x01(\t\x12\x0c\n\x04\x61rea\x18\x07 \x01(\t\x12\x13\n\x0bsource_name\x18\x08 \x01(\t\x12\x19\n\x11\x65vent_category_id\x18\t \x01(\x05\x12\x1b\n\x13\x65vent_category_name\x18\n \x01(\t\x12\x16\n\x0e\x63ondition_name\x18\x0b \x01(\t\x12\x1a\n\x12sub_condition_name\x18\x0c \x01(\t\x12\x15\n\ralarm_message\x18\r \x01(\t\x12\x19\n\x11\x63ondition_quality\x18\x0e \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x0f \x01(\t\x12\x14\n\x0c\x61\x63k_Required\x18\x10 \x01(\x08\x12\x13\n\x0b\x63hange_mask\x18\x11 \x01(\x05\x12\x11\n\tnew_state\x18\x12 \x01(\x05\x12\x13\n\x0b\x61\x63tive_time\x18\x13 \x01(\x03\x12\x0c\n\x04time\x18\x14 \x01(\x03\x12\x15\n\rbak_attribute\x18\x15 \x01(\t*]\n\nevent_type\x12\x08\n\x04NONE\x10\x00\x12\x14\n\x10OPC_SIMPLE_EVENT\x10\x01\x12\x16\n\x12OPC_TRACKING_EVENT\x10\x02\x12\x17\n\x13OPC_CONDITION_EVENT\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_EVENT_TYPE = _descriptor.EnumDescriptor(
  name='event_type',
  full_name='com.richisland.proto.event_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPC_SIMPLE_EVENT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPC_TRACKING_EVENT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPC_CONDITION_EVENT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=566,
  serialized_end=659,
)
_sym_db.RegisterEnumDescriptor(_EVENT_TYPE)

event_type = enum_type_wrapper.EnumTypeWrapper(_EVENT_TYPE)
NONE = 0
OPC_SIMPLE_EVENT = 1
OPC_TRACKING_EVENT = 2
OPC_CONDITION_EVENT = 3



_PB_DATA_OPCALARM = _descriptor.Descriptor(
  name='pb_data_opcalarm',
  full_name='com.richisland.proto.pb_data_opcalarm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opcalarm_data_id', full_name='com.richisland.proto.pb_data_opcalarm.opcalarm_data_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_publish', full_name='com.richisland.proto.pb_data_opcalarm.is_publish', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='com.richisland.proto.pb_data_opcalarm.event_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='severity', full_name='com.richisland.proto.pb_data_opcalarm.severity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_address', full_name='com.richisland.proto.pb_data_opcalarm.server_address', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_prog_id', full_name='com.richisland.proto.pb_data_opcalarm.server_prog_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area', full_name='com.richisland.proto.pb_data_opcalarm.area', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_name', full_name='com.richisland.proto.pb_data_opcalarm.source_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_category_id', full_name='com.richisland.proto.pb_data_opcalarm.event_category_id', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_category_name', full_name='com.richisland.proto.pb_data_opcalarm.event_category_name', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='condition_name', full_name='com.richisland.proto.pb_data_opcalarm.condition_name', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_condition_name', full_name='com.richisland.proto.pb_data_opcalarm.sub_condition_name', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alarm_message', full_name='com.richisland.proto.pb_data_opcalarm.alarm_message', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='condition_quality', full_name='com.richisland.proto.pb_data_opcalarm.condition_quality', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actor_id', full_name='com.richisland.proto.pb_data_opcalarm.actor_id', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ack_Required', full_name='com.richisland.proto.pb_data_opcalarm.ack_Required', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='change_mask', full_name='com.richisland.proto.pb_data_opcalarm.change_mask', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_state', full_name='com.richisland.proto.pb_data_opcalarm.new_state', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_time', full_name='com.richisland.proto.pb_data_opcalarm.active_time', index=18,
      number=19, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='com.richisland.proto.pb_data_opcalarm.time', index=19,
      number=20, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bak_attribute', full_name='com.richisland.proto.pb_data_opcalarm.bak_attribute', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=564,
)

_PB_DATA_OPCALARM.fields_by_name['event_type'].enum_type = _EVENT_TYPE
DESCRIPTOR.message_types_by_name['pb_data_opcalarm'] = _PB_DATA_OPCALARM
DESCRIPTOR.enum_types_by_name['event_type'] = _EVENT_TYPE

pb_data_opcalarm = _reflection.GeneratedProtocolMessageType('pb_data_opcalarm', (_message.Message,), dict(
  DESCRIPTOR = _PB_DATA_OPCALARM,
  __module__ = 'pb_data_opcalarm'
  # @@protoc_insertion_point(class_scope:com.richisland.proto.pb_data_opcalarm)
  ))
_sym_db.RegisterMessage(pb_data_opcalarm)


# @@protoc_insertion_point(module_scope)
